site_name: 在线招聘欺诈检测
theme:
  name: material
  lang: zh
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - content.code.copy
  code:
    highlight_theme: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
site_author: "周伟诺"
site_description: "基于模型融合的在线招聘欺诈检测"
repo_name: FakeJobDetection
repo_url: https://github.com/ZenCoder-art/ofd
nav:
  - Introduction: index.md
  - Get Started:
      - 快速开始: Home/quick.md
      - 环境配置: Home/install.md
  - Model:
      - 数据描述: data/info.md
      - 数据预处理与特征工程: data/process.md
      - 训练模型: model/train.md
      - 模型评估: model/evaluate.md
  - API: api.md
  - About: about.md
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZenCoder-art/ofd
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/astral-sh
    - icon: fontawesome/solid/paper-plane
      link: mailto:weinuozhou@outlook.com
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/astral_sh
markdown_extensions:
  toc:
    permalink: true
  admonition: {}
